idf_component_register(
    SRCS
        "main.c"
        "wifi.c"
        "ota.c"
        "telemetry.c"
    INCLUDE_DIRS "."
    REQUIRES
        metrics
        detools
        esp_partition
        app_update
        esp_http_client
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        mbedtls
        json
        bootloader_support
        driver
        mqtt
        esp_app_format
)