name: CI_CD

on:
  push:
    branches:
      - Integration_Github-Actions-AWS

# Required for OIDC connection with AWS
permissions:
  id-token: write
  contents: read

jobs:
  Automate:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Download the source code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Build the ESP32 Firmware using ESP-IDF toolchain
      - name: Setup ESP-IDE
        uses: espressif/esp-idf-ci-action@v1
        with:
          version: v5.1
          target: esp32
          command: idf.py build

      # Step 3: Archive the built binaries as a GitHub Artifact
      - name: Upload firmware as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware-bin
          path: build/*.bin

      # Step 4: Authenticate with AWS using OIDC and IAM Role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1 # Ensure this matches your S3 Bucket region
          role-session-name: GitHubActionsOIDC

      # Step 5: List files (to debug where the .bin is)
      - name: List files in build directory
        run: find build -name "*.bin"

       # Step 6: Generate Metadata and Upload to Amazon S3
      - name: Generate Metadata and Upload to S3
        run: |
          # 1. Give permissions to the build directory first
          sudo chmod -R 777 build
          
          # 2. Generate versioning and security metadata
          VERSION_NUM="${{ github.run_number }}"
          FILE_HASH=$(sha256sum build/wifi_station.bin | cut -d ' ' -f 1)
          
          # 3. Create the metadata.json file
          echo "{\"version\": \"$VERSION_NUM\", \"hash\": \"$FILE_HASH\", \"file\": \"wifi_station.bin\"}" > build/metadata.json
          
          # 4. Upload all .bin files and the metadata.json to S3
          aws s3 cp build/ s3://esp32-firmware-rewaa/ --recursive --exclude "*" --include "*.bin" --include "metadata.json"
